### ISSUE TITLE
About the batch size

### ISSUE THREAD

**Issue by pcl111** [minghchen/MaxSquareLoss#5]
In your code, I find you set the batch size to 1. I want to know whether a larger batch size can lead to better performance. Thank you.

**Comment by minghchen** [comment]
We set the batch_size to 1 because it fits in one 1080ti. If you set a larger batch size, you need to run the model parallelly on multiple GPUs. We have not tested the performance of a larger batch size due to limited computing resources. You can test by yourself and add nn.DataParallel to the model in train_source.py:
`self.model = nn.DataParallel(self.model, device_ids=range(ceil(len(self.args.gpu)/2)))`

You might also need sync_batchnorm that can be found in https://github.com/hualin95/Deeplab-v3plus, although we haven't tested it.
